### ISSUE TITLE
4A: Choose a suitable logging library

### ISSUE THREAD

**Issue by kkramer215** [sfuphantom/DAQ#16]
This is a research task to weigh the pros and cons of different libraries to ensure that they enable what we need. I recommend playing around in a new project to get a sense of how others might use the API. Here’s an intro link to get started. [ESP32 Logging • ThingPulse](https://thingpulse.com/esp32-logging/)

Some metrics to consider (in no particular order):
Ease of use
Colors! (Though we can always add our own)
Log levels
Ability to save to an SD card
Language (C/C++) ie is it object oriented or functional

**Comment by rafguevara14** [comment]
https://thingpulse.com/esp32-logging/

**Comment by Andromas14** [comment]
Arduino-Log (https://github.com/thijse/Arduino-Log) is the best candidate for a logging library to use along with the built-in ESP32 logger. The other libraries researched could also have specific use cases in the future if needed.

Research Summary Doc:
https://docs.google.com/document/d/1bXmvKOGXHvtMauRjWnox6od5YsSQDtnRrv-VulEEWuo/edit?usp=share_link
