### ISSUE TITLE
1D: Consolidate wiring between DAQ board and ESP32 microcontroller

### ISSUE THREAD

**Issue by rafguevara14** [sfuphantom/DAQ#19]

**Comment by rafguevara14** [comment]
Hardware docs:
 https://drive.google.com/drive/u/0/folders/1nM0JWtPDw11XXwn8rOav-SsgN25pjPbE

ESP32 model: 
https://docs.platformio.org/en/latest/boards/espressif32/esp32dev.html?utm_source=platformio&utm_medium=piohome

**Comment by arrsh** [comment]
![image](https://user-images.githubusercontent.com/43916638/213893177-c3cbb152-3bb1-4244-9eae-1837f351d6fd.png)
ESP32 Pinout: https://docs.platformio.org/en/latest/platforms/espressif32.html#platform-espressif32
Required connections: 

2,4 : 5V       : 5V
--   : 3V3     : 3V3
39  : GND   : GND
29  : ADC4  : IO32
26  : ADC5  : IO33
36  : GPIO0 : IO0
31  : GPIO2 : IO2
32  : GPIO4 : IO4

DAQ : Pin type: ESP 32 pin name

**Comment by rafguevara14** [comment]
You're looking at the wrong pins on the DAQ side for the ADC. If you look at the [datasheet](https://www.ti.com/lit/ds/symlink/ads1115.pdf?ts=1674350609823&ref_url=https%253A%252F%252Fwww.ti.com%252Fproduct%252FADS1115%252Fpart-details%252FADS1115IDGST%253Futm_source%253Dgoogle%2526utm_medium%253Dcpc%2526utm_campaign%253Docb-tistore-promo-asc_opn_en-cpc-storeic-google-wwe%2526utm_content%253DDevice%2526ds_k%253DADS1115IDGST%2526DCM%253Dyes%2526gclid%253DCj0KCQiAt66eBhCnARIsAKf3ZNGBAjN1dzretbfBXml6uhXmq-_xPD_48973F1NQDsk_nAqeRiB7wq8aAuWMEALw_wcB%2526gclsrc%253Daw.ds), these are alert pins to let us know 
that the ADC is ready for sampling/conversion. The pins you want are pins 3 and 5 (SCL/SDA) on the DAQ board for I2C peripheral (not SPI like I thought) to go somewhere on the ESP32. Alert pins are still useful tho! 

Don't be deceived by the ADC4/5 on the ESP32 they are internal ADCs that we won't use because the input voltage range isn't enough for our application.

![image](https://user-images.githubusercontent.com/66582348/213896492-339f5a04-9c46-4c3b-99ca-3c8e46f12f37.png)

**Comment by arrsh** [comment]
Updated as per feedback:

2,4 : 5V : 5V
-- : 3V3 : 3V3
39 : GND : GND
**ADC (I2C and ALERTs)**
3   : SCL   : IO22
5   : SDA  : IO21
29 : GPIO16 : IO16
26 : GPIO17 : IO17
**MUX**
36 : GPIO0 : IO0
31 : GPIO2 : IO2
32 : GPIO4 : IO4 

DAQ side : Pin type: ESP 32 pin name

**Comment by rafguevara14** [comment]
LGTM! Moving to done. I'm asking Power where the hardware is. Once we have that we can try connecting everything. Until then, I'll assign you another task and we can talk about it at the next DAQ meeting

**Comment by arrsh** [comment]
Ack.
Thanks
